# Project information
site_name: Siv3D_Multiplayer_Photon
site_url: https://siv3d.github.io/ja-jp/
site_author: Ryo Suzuki
site_description: "Siv3D: 創造のための C++ フレームワーク" 

# Repository
repo_name: Siv3D/OpenSiv3D
repo_url: https://github.com/Siv3D/OpenSiv3D

# Copyright
copyright: Copyright (c) 2012 - 2023, Ryo Suzuki<br>Copyright (c) 2012 - 2023, OpenSiv3D Project

# Theme
theme:
  name: material
  language: ja
  palette:
    scheme: siv3d
  logo: 'assets/code-white-48dp.svg'
  favicon: 'assets/favicon.ico'
  features:
  - navigation.instant
  - navigation.top
  - navigation.footer
  - search.suggest
  - search.highlight
  - content.code.annotate
  - content.code.copy
  plugins:
  - search:
      lang:
        - ja
extra_css:
  - "https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css"
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
      toc_depth: 3
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  alternate:
    - name: 日本語
      link: https://siv3d.github.io/ja-jp/
      lang: ja
    - name: English
      link: https://siv3d.github.io/en-us/
      lang: en

# Page tree
nav:
  - Siv3D でオンラインゲームをつくろう: index.md
  - Siv3D for Web でオンラインゲームをつくろう: web.md
  - 動かしてみよう: verify_the_connection.md
  - 基礎のプログラム: foundation.md
  - コールバック: call_back.md
  - イベント送受信: event_send_receive.md
    